name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy black pytest
          pip install -e .
      - name: Configure test DB path
        run: |
          # Use an isolated DB file inside the runner workspace for tests
          export TWITCHBUDDY_DB_PATH="$GITHUB_WORKSPACE/twitchbuddy-ci-test.db"
          export TWITCHBUDDY_DATA_DIR="$GITHUB_WORKSPACE/.local/share/twitchbuddy"
          echo "TWITCHBUDDY_DB_PATH=$TWITCHBUDDY_DB_PATH" >> $GITHUB_ENV
          echo "TWITCHBUDDY_DATA_DIR=$TWITCHBUDDY_DATA_DIR" >> $GITHUB_ENV
      - name: Lint (ruff)
        run: ruff check .
      - name: Type check (mypy)
        run: mypy src tests
      - name: Format check (black)
        run: black --check .
      - name: Tests
        run: pytest -q
